In [15]:
import requests
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/huggingface/transformers/refs/heads/main/MIGRATION_GUIDE_V5.md"

In [4]:
# Downloading
response = requests.get(url)
response.raise_for_status()

whole_text = response.text

print("Characters:", len(whole_text))
print(whole_text[:1000])

Characters: 44657
<!---
Copyright 2025 The HuggingFace Team. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

# Version 5 Migration guide

## Library-wide changes with widespread impact

### Removal of TensorFlow and Jax

We're removing the TensorFlow and Jax parts of the library. This will help us focus fully on `torch`
going forward and will greatly reduce the maintenance cost of models. We are working with tools from
the Jax ecosystem still (such as MaxText) in order to see how we can remain compatible with

In [5]:
headings = []
code = False                      # initially looking for just the # character was giving code comments too

for line in whole_text.splitlines():
  if line.strip().startswith("```"):
    if code == True:
      code = False
    else:
      code = True
    continue
  if not code and line.startswith("#"):
    headings.append(line)

print("Heading numbers:", len(headings))

for heading in headings:
  print(heading)

Heading numbers: 58
# Version 5 Migration guide
## Library-wide changes with widespread impact
### Removal of TensorFlow and Jax
### Dynamic weight loading
## Tokenization
### Backend Architecture Changes: moving away from the slow/fast tokenizer separation
### Defining a tokenizers outside of the existing backends
### API Changes
#### 1. Direct tokenizer initialization with vocab and merges
#### 2. Simplified decoding API
#### 3. Unified encoding API
#### 4. `apply_chat_template` returns `BatchEncoding`
#### 5. Removed legacy configuration file saving:
#### 6. Model-Specific Changes
### Testing Changes
#### 7. Deprecated / Modified Features
## Disclaimers for the RC0
### PEFT + MoE:
### Tensor parallel and Expert parallel + MoE
### Remote code incompatibility
### Custom pretrained models:
## Library-wide changes with lesser impact
### Drop support for `safe_serialization=False`
### 50GB default shard size
### `use_auth_token`
### Attention-related features
### Updates to supported torch APIs
### Feature extraction helpers: `get_*_features`
## Quantization changes
### Auto-classes
## Configuration
## Processing
### Tokenization
### Processing classes
### Image processors
#### `use_fast` is replaced by `backend`
#### `FooImageProcessorFast` class names are deprecated
#### `is_fast` property is deprecated
#### `AutoImageProcessor.register()` API change
#### Custom backends
## Modeling
### Generate
## Trainer
### Removing arguments without deprecation cycle in `TrainingArguments` due to low usage
### Removing deprecated arguments in `TrainingArguments`
### Removing deprecated arguments in `Trainer`
### Removed features for `Trainer`
###  New defaults for `Trainer`
## Pipelines
### Text pipelines that should just be LLMs
### Vision pipelines that should just be VLMs
### Other removed pipelines
### Other changes
## PushToHubMixin
## CLI
### Removal of the `run` method
## Environment variables
## Requirements update

In [11]:
sections = []
main_section = None
subsection = None
subsubsection = None
current = []
code = False
title = None

for line in whole_text.splitlines():
  stripped = line.strip()
  if stripped.startswith("```"):
    if not code:
      code = True
    else:
      code = False
    current.append(line)
    continue
  if code:
    current.append(line)
    continue
  if line.startswith("#### "):
    text = "\n".join(current).strip()
    if text:
      sections.append({
          "main_section": main_section,
          "subsection": subsection,
          "subsubsection": subsubsection,
          "text": text
      })
    subsubsection = line[5:].strip()
    current = []
  elif line.startswith("### "):
    text = "\n".join(current).strip()
    if text:
      sections.append({
          "main_section": main_section,
          "subsection": subsection,
          "subsubsection": subsubsection,
          "text": text
      })
    subsection = line[4:].strip()
    subsubsection = None
    current = []
  elif line.startswith("## "):
    text = "\n".join(current).strip()
    if text:
      sections.append({
          "main_section": main_section,
          "subsection": subsection,
          "subsubsection": subsubsection,
          "text": text
      })
    main_section = line[3:].strip()
    subsection = None
    subsubsection = None
    current = []
  elif line.startswith("# "):
    title = line[2:].strip()
  else:
    current.append(line)

text = "\n".join(current).strip()

if text:
  sections.append({
      "main_section": main_section,
      "subsection": subsection,
      "subsubsection": subsubsection,
      "text": text
  })



for i, section in enumerate(sections):
    print(f"SECTION {i + 1}")

    print("Main:", section["main_section"])
    print("Sub:", section["subsection"])
    print("Sub-sub:", section["subsubsection"])

    print("Text:")
    print(section["text"])

    print("-" * 80)

SECTION 1
Main: None
Sub: None
Sub-sub: None
Text:
<!---
Copyright 2025 The HuggingFace Team. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
--------------------------------------------------------------------------------
SECTION 2
Main: Library-wide changes with widespread impact
Sub: Removal of TensorFlow and Jax
Sub-sub: None
Text:
We're removing the TensorFlow and Jax parts of the library. This will help us focus fully on `torch`
going forward and will greatly reduce the maintenance cost of models. We are working with tools from
the Jax ecosystem still (such as MaxText) in order to see how we can remain compatible with their
tool while keeping `torch` as the only backend for now.

Linked PR: https://github.com/huggingface/transformers/pull/40760
--------------------------------------------------------------------------------
SECTION 3
Main: Library-wide changes with widespread impact
Sub: Dynamic weight loading
Sub-sub: None
Text:
We introduce a new weight loading API in `transformers`, which significantly improves on the previous API. This
weight loading API is designed to apply operations to the checkpoints loaded by transformers.

Instead of loading the checkpoint exactly as it is serialized within the model, these operations can reshape, merge,
and split the layers according to how they're defined in this new API. These operations are often a necessity when
working with quantization or parallelism algorithms.

This new API is centered around the new `WeightConverter` class:

```python
class WeightConverter(WeightTransform):
    operations: list[ConversionOps]
    source_keys: Union[str, list[str]]
    target_keys: Union[str, list[str]]
```

The weight converter is designed to apply a list of operations on the source keys, resulting in target keys. A common
operation done on the attention layers is to fuse the query, key, values layers. Doing so with this API would amount
to defining the following conversion:

```python
conversion = WeightConverter(
    ["self_attn.q_proj", "self_attn.k_proj", "self_attn.v_proj"],  # The input layers
    "self_attn.qkv_proj",  # The single layer as output
    operations=[Concatenate(dim=0)],
)
```

In this situation, we apply the `Concatenate` operation, which accepts a list of layers as input and returns a single
layer.

This allows us to define a mapping from architecture to a list of weight conversions. Applying those weight conversions
can apply arbitrary transformations to the layers themselves. This significantly simplified the `from_pretrained` method
and helped us remove a lot of technical debt that we accumulated over the past few years.

This results in several improvements:
- Much cleaner definition of transformations applied to the checkpoint
- Reversible transformations, so loading and saving a checkpoint should result in the same checkpoint
- Faster model loading thanks to scheduling of tensor materialization
- Enables complex mix of transformations that wouldn't otherwise be possible (such as quantization + MoEs, or TP + MoEs)

While this is being implemented, expect varying levels of support across different release candidates.

Linked PR: https://github.com/huggingface/transformers/pull/41580
--------------------------------------------------------------------------------
SECTION 4
Main: Tokenization
Sub: None
Sub-sub: None
Text:
Just as we moved towards a single backend library for model definition, we want our tokenizers, and the `Tokenizer` object to be a lot more intuitive. With v5, tokenizer definition is much simpler; one can now initialize an empty `LlamaTokenizer` and train it directly on your corpus.

Defining a new tokenizer object should be as simple as this:

```python
from transformers import TokenizersBackend, generate_merges
from tokenizers import pre_tokenizers, Tokenizer
from tokenizers.model import BPE

class Llama5Tokenizer(TokenizersBackend):
    def __init__(self, unk_token="<unk>",bos_token="<s>", eos_token="</s>", vocab=None, merges=None ):
        if vocab is None:
            self._vocab = {
                str(unk_token): 0,
                str(bos_token): 1,
                str(eos_token): 2,
            }

        else:
            self._vocab = vocab

        self._merges = merges or []

        self._tokenizer = Tokenizer(
            BPE(vocab=self._vocab, merges=self._merges, fuse_unk=True)
        )
        self._tokenizer.pre_tokenizer = pre_tokenizers.Metaspace(
            replacement="▁", prepend_scheme=_get_prepend_scheme(self.add_prefix_space, self), split=False
        )
        super().__init__(
            tokenizer_object=self._tokenizer,
            unk_token=unk_token,
            bos_token=bos_token,
            eos_token=eos_token,
        )
```

Once the tokenizer is defined as above, you can load it with the following: `Llama5Tokenizer()`. Doing this returns you an empty, trainable tokenizer that follows the definition of the authors of `Llama5` (it does not exist yet :wink:).

The above is the main motivation towards refactoring tokenization: we want tokenizers to behave similarly to models: trained or empty, and with exactly what is defined in their class definition.
--------------------------------------------------------------------------------
SECTION 5
Main: Tokenization
Sub: Backend Architecture Changes: moving away from the slow/fast tokenizer separation
Sub-sub: None
Text:
Up to now, transformers maintained two parallel implementations for many tokenizers:
- "Slow" tokenizers (`tokenization_<model>.py`) - Python-based implementations, often using [SentencePiece](https://github.com/google/sentencepiece) as the backend.
- "Fast" tokenizers (`tokenization_<model>_fast.py`) - Rust-based implementations using the 🤗 [tokenizers](https://github.com/huggingface/tokenizers) library.

In v5, we consolidate to a single tokenizer file per model: `tokenization_<model>.py`. This file will use the most appropriate backend available:

1. **TokenizersBackend** (preferred): Rust-based tokenizers from the 🤗 [tokenizers](https://github.com/huggingface/tokenizers) library. In general it provides optimal performance, but it also offers a lot more features that are commonly adopted across the ecosystem:
  - handling additional tokens
  - a full python API for setting and updating
  - automatic parallelization,
  - automatic offsets
  - customization
  - training
2. **SentencePieceBackend**: for tokenizers requiring the `sentencepiece` library. It inherits from `PythonBackend`.
3. **PythonBackend**: a Python implementations of the features provided by `tokenizers`. Basically allows adding tokens.
4. **MistralCommonBackend**: relies on `MistralCommon`'s tokenization library. (Previously known as the `MistralCommonTokenizer`)

The `AutoTokenizer` automatically selects the appropriate backend based on available files and dependencies. This is transparent, you continue to use `AutoTokenizer.from_pretrained()` as before. This allows transformers to be future-proof and modular to easily support future backends.
--------------------------------------------------------------------------------
SECTION 6
Main: Tokenization
Sub: Defining a tokenizers outside of the existing backends
Sub-sub: None
Text:
We enable users and tokenizer builders to define their own tokenizers from top to bottom. Tokenizers are usually defined using a backend such as `tokenizers`, `sentencepiece` or `mistral-common`, but we offer the possibility to design the tokenizer at a higher-level, without relying on those backends.

To do so, you can import the `PythonBackend` (which was previously known as `PreTrainedTokenizer`). This class encapsulates all the logic related to added tokens, encoding, and decoding.

If you want something even higher up the stack, then `PreTrainedTokenizerBase` is what `PythonBackend` inherits from. It contains the very basic tokenizer API features:
- `encode`
- `decode`
- `vocab_size`
- `get_vocab`
- `convert_tokens_to_ids`
- `convert_ids_to_tokens`
- `from_pretrained`
- `save_pretrained`
- among a few others

**Note for implementing new tokenizers:** When creating a tokenizer class that loads from SentencePiece files, you can override the `convert_from_spm` class method in your converter to customize vocabulary structure, normalizers, regexes and anything that you would want to be passed to the tokenizers your are converting.
This is useful if the model requires specific token ordering or special split regex patterns. See existing converter classes in `convert_slow_tokenizer.py` for examples.
--------------------------------------------------------------------------------
SECTION 7
Main: Tokenization
Sub: API Changes
Sub-sub: 1. Direct tokenizer initialization with vocab and merges
Text:
Starting with v5, we now enable initializing blank, untrained `tokenizers`-backed tokenizers:

```py
from transformers import LlamaTokenizer

tokenizer = LlamaTokenizer()
```

This tokenizer will therefore follow the definition of the `LlamaTokenizer` as defined in its class definition. It can then be trained on a corpus as can be seen in [the `tokenizers` documentation](https://huggingface.co/docs/tokenizers/training_from_memory).

These tokenizers can also be initialized from vocab and merges (if necessary), like the previous "slow" tokenizers:

```py
from transformers import LlamaTokenizer

vocab = {"<unk>": 0, "<s>": 1, "</s>": 2, "hello": 3, "world": 4}
merges = [("h", "e"), ("l", "l"), ("o", " ")]

tokenizer = LlamaTokenizer(vocab=vocab, merges=merges)
```

This tokenizer will behave as a Llama-like tokenizer, with an updated vocabulary. This allows comparing different tokenizer classes with the same vocab; therefore enabling the comparison of different pre-tokenizers, normalizers, etc.

**Simplified file loading:** Support is added for passing`vocab` and `merges` as file paths directly to tokenizer initialization. The tokenizer will automatically detect the format (SentencePiece `.model`, Tekken `tekken.json`, or plain vocab/merges files) for loading. For BPE tokenizers, if a vocab is provided but no merges, merges will be automatically generated (excluding special tokens).

Note: Loading from file paths with `vocab="<path_to_a_file>"`'s primary goal is to allow you to do some quick testing, but for `BPE` models for example we don't check whether you properly passed the merges or not.
--------------------------------------------------------------------------------
SECTION 8
Main: Tokenization
Sub: API Changes
Sub-sub: 2. Simplified decoding API
Text:
The `batch_decode` and `decode` methods have been unified to reflect behavior of the `encode` method. Both single and batch decoding now use the same `decode` method. See an example of the new behavior below:

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("t5-small")
inputs = ["hey how are you?", "fine"]
tokenizer.decode(tokenizer.encode(inputs))
```

Gives:
```diff
- 'hey how are you?</s> fine</s>'
+ ['hey how are you?</s>', 'fine</s>']
```

We expect `encode` and `decode` to behave, as two sides of the same coin: `encode`, `process`, `decode`,  should work.

> [!NOTE]
> A common use-case would be: `encode`, `model.generate`, `decode`.  However, using `generate` would return `list[list[int]]`, which would then be incompatible with `decode`.
--------------------------------------------------------------------------------
SECTION 9
Main: Tokenization
Sub: API Changes
Sub-sub: 3. Unified encoding API
Text:
The `encode_plus` method is deprecated in favor of the single `__call__` method.
--------------------------------------------------------------------------------
SECTION 10
Main: Tokenization
Sub: API Changes
Sub-sub: 4. `apply_chat_template` returns `BatchEncoding`
Text:
Previously, `apply_chat_template` returned `input_ids` for backward compatibility. Starting with v5, it now consistently returns a `BatchEncoding` dict like other tokenizer methods.

```python
# v5
messages = [
    {"role": "user", "content": "Hello!"},
    {"role": "assistant", "content": "Hi there!"}
]

# Now returns BatchEncoding with input_ids, attention_mask, etc.
outputs = tokenizer.apply_chat_template(messages, return_tensors="pt")
print(outputs.keys())  # dict_keys(['input_ids', 'attention_mask'])
```
--------------------------------------------------------------------------------
SECTION 11
Main: Tokenization
Sub: API Changes
Sub-sub: 5. Removed legacy configuration file saving:
Text:
We simplify the serialization of tokenization attributes:

- `special_tokens_map.json` - special tokens are now stored in `tokenizer_config.json`.
- `added_tokens.json` - added tokens are now stored in `tokenizer.json`.
- `added_tokens_decoder` is only stored when there is no `tokenizer.json`.
- `add_bos_token` and `add_eos_token` - these are no longer saved in `tokenizer_config.json`. When a `tokenizer.json` file exists, these settings are defined in the tokenizer class or `tokenizer.json` itself.

**Backend synchronization removed:** The automatic synchronization logic that updated backend tokenizer settings (like `add_prefix_space`, `do_lower_case`, `strip_accents`, `tokenize_chinese_chars`) after initialization has been removed. Tokenizer behavior is now fully determined by the `tokenizer.json` file or class definition at initialization time.

When loading older tokenizers, these files are still read for backward compatibility, but new saves use the consolidated format. We're gradually moving towards consolidating attributes to fewer files so that other libraries and implementations may depend on them more reliably.
--------------------------------------------------------------------------------
SECTION 12
Main: Tokenization
Sub: API Changes
Sub-sub: 6. Model-Specific Changes
Text:
Several models that had identical tokenizers now import from their base implementation:

- **LayoutLM** → uses BertTokenizer
- **LED** → uses BartTokenizer
- **Longformer** → uses RobertaTokenizer
- **LXMert** → uses BertTokenizer
- **MT5** → uses T5Tokenizer
- **MVP** → uses BartTokenizer
These modules will eventually be removed altogether.

**Removed T5-specific workarounds**

The internal `_eventually_correct_t5_max_length` method has been removed. T5 tokenizers now handle max length consistently with other models.
--------------------------------------------------------------------------------
SECTION 13
Main: Tokenization
Sub: Testing Changes
Sub-sub: None
Text:
A few testing changes specific to tokenizers have been applied:
- Model-specific tokenization test files now focus on integration tests.
- Common tokenization API tests (e.g., `add_tokens`, `encode`, `decode`) are now centralized and automatically applied across all tokenizers. This reduces test duplication and ensures consistent behavior

For legacy implementations, the original BERT Python tokenizer code (including `WhitespaceTokenizer`, `BasicTokenizer`, etc.) is preserved in `bert_legacy.py` for reference purposes.
--------------------------------------------------------------------------------
SECTION 14
Main: Tokenization
Sub: Testing Changes
Sub-sub: 7. Deprecated / Modified Features
Text:
**Special Tokens Structure:**
- `SpecialTokensMixin`: Merged into `PreTrainedTokenizerBase` to simplify the tokenizer architecture.
- `special_tokens_map`: Now only stores named special token attributes (e.g., `bos_token`, `eos_token`). Use `extra_special_tokens` for additional special tokens (formerly `additional_special_tokens`). `all_special_tokens` includes both named and extra tokens.

```python
# v4
tokenizer.special_tokens_map  # Included 'additional_special_tokens'

# v5
tokenizer.special_tokens_map  # Only named tokens
tokenizer.extra_special_tokens  # Additional tokens
```

- `special_tokens_map_extended` and `all_special_tokens_extended`: Removed. Access `AddedToken` objects directly from `_special_tokens_map` or `_extra_special_tokens` if needed.
- `additional_special_tokens`: Automatically converted to `extra_special_tokens` during initialization.
- `additional_special_tokens_ids`: Removed. Use `extra_special_tokens_ids` instead.
- `extra_special_tokens`: Only accepts list/tuple format and is intended for use during tokenizer initialization. For model-specific named tokens (e.g., `image_token`), pass directly as keyword arguments instead.

**Deprecated Methods:**
- `sanitize_special_tokens()`: Already deprecated in v4, removed in v5.
- `prepare_seq2seq_batch()`: Deprecated; use `__call__()` with `text_target` parameter instead.

```python
# v4
model_inputs = tokenizer.prepare_seq2seq_batch(src_texts, tgt_texts, max_length=128)

# v5
model_inputs = tokenizer(src_texts, text_target=tgt_texts, max_length=128, return_tensors="pt")
model_inputs["labels"] = model_inputs.pop("input_ids_target")
```

- `BatchEncoding.words()`: Deprecated; use `word_ids()` instead.

**Removed Methods:**
- `create_token_type_ids_from_sequences()`: Removed from base class. Subclasses that need custom token type ID creation should implement this method directly.
- `prepare_for_model()`, `build_inputs_with_special_tokens()`, `truncate_sequences()`: Moved from `tokenization_utils_base.py` to `tokenization_python.py` for `PythonBackend` tokenizers. `TokenizersBackend` provides model-ready input via `tokenize()` and `encode()`, so these methods are no longer needed in the base class.
- `_switch_to_input_mode()`, `_switch_to_target_mode()`, `as_target_tokenizer()`: Removed from base class. Use `__call__()` with `text_target` parameter instead.

```python
# v4
with tokenizer.as_target_tokenizer():
    labels = tokenizer(tgt_texts, ...)

# v5
labels = tokenizer(text_target=tgt_texts, ...)
```

- `parse_response()`: Removed from base class.
--------------------------------------------------------------------------------
SECTION 15
Main: Disclaimers for the RC0
Sub: PEFT + MoE:
Sub-sub: None
Text:
Because we are switching from the naive MOE (`nn.ModuleList` for experts) we currently have an issue with MoEs that have adapters. For more details see https://github.com/huggingface/transformers/issues/42491#issuecomment-3591485649.

_We aim for this to be fixed and released in a following release candidate in the week that follows RC0._
--------------------------------------------------------------------------------
SECTION 16
Main: Disclaimers for the RC0
Sub: Tensor parallel and Expert parallel + MoE
Sub-sub: None
Text:
We are streamlining the MoE support with vLLM; while this is being implemented, tensor parallelism and expert parallelism aren't working as expected.
This is known and actively being worked on.

_We aim for this to be fixed and released in a following release candidate in the week that follows RC0._
--------------------------------------------------------------------------------
SECTION 17
Main: Disclaimers for the RC0
Sub: Remote code incompatibility
Sub-sub: None
Text:
A lot of paths were removed and reworked; paths like `transformers.tokenization_utils` and `transformers.tokenization_utils_fast`, which no longer exist.
These now redirect to `transformers.tokenization_utils_sentencepiece` and `transformers.tokenization_utils_tokenizers` respectively; please update imports accordingly.

_We aim for this to be fixed and released in a following release candidate in the week that follows RC0._
--------------------------------------------------------------------------------
SECTION 18
Main: Disclaimers for the RC0
Sub: Custom pretrained models:
Sub-sub: None
Text:

In [13]:
print("Title:", title)
print("Number of records parsed:", len(sections))
print("First section:", sections[1]["main_section"])
print("Last section:", sections[-1]["main_section"])

Title: Version 5 Migration guide
Number of records parsed: 51
First section: Library-wide changes with widespread impact
Last section: Requirements update

In [19]:
df = pd.DataFrame(sections)

df.head()
print(df.shape)
print(df.isna().sum())
df = df[df["main_section"].notna()].copy()
print(df.shape)
df.head()

(51, 4)
main_section      1
subsection        9
subsubsection    39
text              0
dtype: int64
(50, 4)

,main_section,subsection,subsubsection,text
1,Library-wide changes with widespread impact,Removal of TensorFlow and Jax,None,We're removing the TensorFlow and Jax parts of...
2,Library-wide changes with widespread impact,Dynamic weight loading,None,We introduce a new weight loading API in `tran...
3,Tokenization,None,None,Just as we moved towards a single backend libr...
4,Tokenization,Backend Architecture Changes: moving away from...,None,"Up to now, transformers maintained two paralle..."
5,Tokenization,Defining a tokenizers outside of the existing ...,None,We enable users and tokenizer builders to defi...

In [20]:
df["version"] = "v5"
df["document_type"] = "migration_guide"
df["source_url"] = url
print(df.shape)
df.head()

(50, 7)

,main_section,subsection,subsubsection,text,version,document_type,source_url
1,Library-wide changes with widespread impact,Removal of TensorFlow and Jax,None,We're removing the TensorFlow and Jax parts of...,v5,migration_guide,https://raw.githubusercontent.com/huggingface/...
2,Library-wide changes with widespread impact,Dynamic weight loading,None,We introduce a new weight loading API in `tran...,v5,migration_guide,https://raw.githubusercontent.com/huggingface/...
3,Tokenization,None,None,Just as we moved towards a single backend libr...,v5,migration_guide,https://raw.githubusercontent.com/huggingface/...
4,Tokenization,Backend Architecture Changes: moving away from...,None,"Up to now, transformers maintained two paralle...",v5,migration_guide,https://raw.githubusercontent.com/huggingface/...
5,Tokenization,Defining a tokenizers outside of the existing ...,None,We enable users and tokenizer builders to defi...,v5,migration_guide,https://raw.githubusercontent.com/huggingface/...

In [26]:
def make_sections(row):
  parts = [row["main_section"], row["subsection"], row["subsubsection"]]
  cleaned = []

  for part in parts:
    if pd.notna(part):
      cleaned.append(part)

  return " > ".join(cleaned)

In [27]:
df["section_path"] = df.apply(make_sections, axis=1)
df[["section_path", "text"]].head(10)

,section_path,text
1,Library-wide changes with widespread impact > ...,We're removing the TensorFlow and Jax parts of...
2,Library-wide changes with widespread impact > ...,We introduce a new weight loading API in `tran...
3,Tokenization,Just as we moved towards a single backend libr...
4,Tokenization > Backend Architecture Changes: m...,"Up to now, transformers maintained two paralle..."
5,Tokenization > Defining a tokenizers outside o...,We enable users and tokenizer builders to defi...
6,Tokenization > API Changes > 1. Direct tokeniz...,"Starting with v5, we now enable initializing b..."
7,Tokenization > API Changes > 2. Simplified dec...,The `batch_decode` and `decode` methods have b...
8,Tokenization > API Changes > 3. Unified encodi...,The `encode_plus` method is deprecated in favo...
9,Tokenization > API Changes > 4. `apply_chat_te...,"Previously, `apply_chat_template` returned `in..."
10,Tokenization > API Changes > 5. Removed legacy...,We simplify the serialization of tokenization ...

In [28]:
df["char_count"] = df["text"].str.len()
df["word_count"] = df["text"].str.split().str.len()

df[["section_path", "char_count", "word_count"]].sort_values("word_count", ascending=False).head(10)

                                         section_path  char_count  word_count
17  Disclaimers for the RC0 > Custom pretrained mo...        3226         314
2   Library-wide changes with widespread impact > ...        2258         313
13  Tokenization > Testing Changes > 7. Deprecated...        2562         248
6   Tokenization > API Changes > 1. Direct tokeniz...        1618         219
47                                                CLI        1459         201
3                                        Tokenization        1822         195
23  Library-wide changes with lesser impact > Feat...        1665         194
4   Tokenization > Backend Architecture Changes: m...        1640         186
5   Tokenization > Defining a tokenizers outside o...        1318         186
26                                      Configuration        1420         179

In [29]:
df.to_csv("migration_guide_sections.csv", index=False)